version: '3.8'

services:

  app:
    image: cornatul/news.ai
    container_name: php_app
    restart: always
    volumes:
      - ./:/var/www/
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:4.0
    container_name: redis_server
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6382:6379"
  nlpservice:
    image: cornatul/nlp:v1
    restart: always
    ports:
      - "9000:9000"
    environment:
      - APP_PORT=9000
    expose:
      - 9000
volumes:
  app_data:
  mysql_data:
  rabbitmq_data:
