version: '3.8'

services:

  app:
    image: cornatul/news.ai
    container_name: app_server
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.nlpservice.rule=Host(`cms.lzomedia.com`)
    networks:
      - app-network
    volumes:
      - ./:/var/www/
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    restart: always
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:4.0
    container_name: redis_server
    networks:
      - app-network
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6382:6379"
#Nlp Service
  nlpservice:
    image: cornatul/nlp:v1
    container_name: nlp_server
    restart: always
    networks:
      - app-network
    ports:
      - "9000:8000"
  traefik:
    image: traefik:v2.3
    restart: always
    container_name: traefik_server
    networks:
      - app-network
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7000:8000"
      - "8080:8080"
# Volumes to be created
volumes:
  app_data:
  mysql_data:
  rabbitmq_data:


# Networks to be created
networks:
  app-network:
