networks:
    cms:
        driver: bridge
services:
    app:
        image: cornatul/news.ai:latest
        environment:
            - CONTAINER_ROLE=ALL
        volumes:
            - .:/var/www/app
        ports:
            - 8080:80
        networks:
            - cms
    db:
        image: mysql:8.0
        cap_add:
            - SYS_NICE
        restart: always
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - cms
        environment:
            - MYSQL_DATABASE=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 9000:8080
        networks:
            - cms
        depends_on:
            - db
    rabbitmq:
        image: 'bitnami/rabbitmq:latest'
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - cms
        environment:
            - RABBITMQ_USERNAME=user
            - RABBITMQ_PASSWORD=user
            - RABBITMQ_VHOST=my_vhost
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        networks:
            - cms
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
        container_name: elasticsearch
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.5.0
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
