version: '3.8'

services:
  app:
    image: cornatul/news.ai
    container_name: php_app
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_PORT: ${DB_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  rabbitmq_data:
